### ISSUE TITLE
Blog post is down

### ISSUE THREAD

**Issue by pmengelbert** [tmdarwen/STM32#1]
I'm really interested in reading your analysis, but it looks like the blog post no longer exists. Do you still have the text laying around somewhere? Maybe you could add it to this repo?

Would be greatly appreciated.

Edit: I should be more specific: This is the blog post in question: http://www.tmdarwen/blog/in-depth-analysis-of-an-arm-cortex-m-program

**Comment by tmdarwen** [comment]
Hi @pmengelbert thanks for bringing this to my attention.  The link has been fixed.
